name: Bundle Update Action

on: workflow_dispatch

jobs:
  build:
    name: Bundle Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1.155.0
        with:
          ruby-version: 3 # ruby version of a project
          bundler-cache: true
      - uses: djdefi/bundle-update-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }} # token of your account
          BRANCH: "maint/bundle-update"
          BASE_BRANCH: main
          REVIEWERS: djdefi
          ASSIGNEES: djdefi
          LABELS: bundle-update
