# This is a basic workflow to help you get started with Actions

name: Auto pages deploy

# Controls when the action will run. Triggers the workflow on push 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/35 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Installs gem deps
    # Renders the page
    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6' # Version range or exact version of a Ruby version to use, using semvers version range syntax.
    - run: |
        gem install bundler
        bundle install
        ruby render.rb

    - name: Git AV Scan
      uses: djdefi/gitavscan@master

    - uses: actions/upload-artifact@v1
      with:
        name: index
        path: public/index.html

    - name: GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v1.3.0
      with:
        build_dir: public
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
