# This is a basic workflow to help you get started with Actions

name: Auto pages deploy

# Controls when the action will run. Triggers the workflow on push 
# events but only for the master branch
on:
  push:
    branches: [ main ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '3 */2 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pages-build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1.138.0
      with:
        ruby-version: '3.1.1' # Version range or exact version of a Ruby version to use, using semvers version range syntax.
        bundler-cache: true
    - run: bundle exec render.rb

    - name: Git AV Scan
      if: success()
      uses: djdefi/gitavscan@main

    - name: Upload build artifact
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: index
        path: public/index.html

    - name: Check Rendered HTML
      if: success()
      uses: chabad360/htmlproofer@master
      continue-on-error: true
      with:
        directory: "./public"
        arguments: "--disable-external"

    - name: GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v3
      with:
        build_dir: public
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
