name: Render Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1.172.0
      with:
        ruby-version: 3.1.1
        bundler-cache: true
    
    - name: Install development dependencies
      run: bundle install --with development

    - name: Run render_test.rb
      run: bundle exec ruby test/render_test.rb
