name: Render Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1.172.0
      with:
        ruby-version: 3.1.1

    - name: Run render.rb
      run: ruby render.rb

    - name: Verify Output
      run: |
        if ! diff -q public/index.html expected/index.html; then
          echo "Render test failed: Output does not match expected result."
          exit 1
        fi
