name: Render Test

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1.190.0
      with:
        ruby-version: '3.4'

    - name: Run render_test.rb
      run: ruby -Itest test/render_test.rb
